### ISSUE TITLE
Bastion Host via AWS CLI - no ssh 22 access

### ISSUE THREAD

**Issue by Dynatrace-BrianWilson** [dt-kube-demo/setup-infra#6]
When creating the Bastion host via command aws command line, the inbound access on the security group was only for the security group, so I could not ssh. I changed inbound source to 0.0.0.0/0 to continue. The default SG does not provide access to ssh, it seems. You had a step in the old PDF to create a security group setting it to open.

**Comment by robertjahn** [comment]
Updated the AWS README with how to do this as part of
https://github.com/dt-kube-demo/setup-infra/commit/e92c7c06dc772b766da3b920f043d0a4a10a3878
