### ISSUE TITLE
5-fork script fails when run from setup.sh

### ISSUE THREAD

**Issue by Dynatrace-BrianWilson** [dt-kube-demo/setup-infra#8]
source org is not defined and the user is given no opportunity to define it.

====================================================
About to fork github repositories with these parameters:

Source : https://github.com/
Target : https://github.com/emperorwilson-awm

Press ctrl-c to abort. Press any key to continue...
====================================================Cloning https://github.com//catalog-service
remote: Repository not found.
fatal: repository 'https://github.com//catalog-service/' not found
./5-forkApplicationRepositories.sh: line 47: cd: catalog-service: No such file or directory
Forking catalog-service to emperorwilson-awm

**Comment by Dynatrace-BrianWilson** [comment]
it also fails when run on its own.

**Comment by robertjahn** [comment]
was missing the variable for source repo.  fixed as part of 
https://github.com/dt-kube-demo/setup-infra/commit/e92c7c06dc772b766da3b920f043d0a4a10a3878
